.NET (javascript, html,css,c#/program2/Models/ErrorViewModel.cs
using System;

namespace assignment_3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

.NET (javascript, html,css,c#/program2/Models/Guest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace assignment_3.Models
{
    public class Guest
    {
        public int Id { get; set; }
        
        [Required]
        [StringLength(200)]
        [DisplayName("Name")]
        public string Name { get; set; }
        
        [Required]
        [MaxLength(50), MinLength(5)]
        [DisplayName("Title ")]
        public string Title { get; set; }
        

        [Required]
        [MaxLength(200), MinLength(20)]
        [DisplayName("Message")]
        public string Message { get; set; }
        
    }
}

.NET (javascript, html,css,c#/program2/Controllers/GuestbookController.cs
using System.Linq;
using assignment_3.Data;
using assignment_3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace assignment_3.Controllers
{
    public class GuestbookController : Controller
    {
        private readonly ILogger<GuestbookController> _logger;
        private readonly ApplicationDbContext _db;
        public GuestbookController(ILogger<GuestbookController> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }
        public IActionResult Index()
        {
            _logger.LogDebug(" fetching guests list");
            return View(_db.Guests.ToList());
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View(new Guest());
        }
        [HttpPost]
        public IActionResult Add(Guest guest)
        {
            _logger.LogDebug("posting a new guest in the book");

            if (!ModelState.IsValid)
            {
                _logger.LogWarning("you have entered something wrong please check again");
                return View(guest);
            }

            _db.Guests.Add(guest);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

.NET (javascript, html,css,c#/program2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using assignment_3.Models;

namespace assignment_3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

.NET (javascript, html,css,c#/program2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

.NET (javascript, html,css,c#/program2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - assignment_3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">assignment_3</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Guestbook" asp-action="Index">guestbook</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Guestbook" asp-action="Add">add</a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - assignment_3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

.NET (javascript, html,css,c#/program2/Views/guestbook/Add.cshtml
@model Guest



<h2>Add Guests</h2>

<p>@ViewBag.Message</p>

<form method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" placeholder="name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" placeholder="title">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Message"></label>
        <input asp-for="Message" class="form-control" placeholder="message">
        <span asp-validation-for="Message" class="text-danger"></span>
    </div>

    <button type="submit" id="Submit" class="btn btn-primary">Submit</button>
</form>

.NET (javascript, html,css,c#/program2/Views/guestbook/Index.cshtml
@model IEnumerable<Guest>


<H2>List of guests</H2>

<table id="guests" class="table table-striped table-bordered">
    <thead>
    <tr><th>name</th><th>Title</th><th>Message</th></tr>
    </thead>
    <tbody>
    <a asp-action="Add" asp-controller="Guestbook">press me</a>
    @foreach (var guest in Model)
    {
        <tr>
            <td>@guest.Name</td><td>@guest.Title</td><td>@guest.Message</td>
        </tr>
    }

    </tbody>
</table>